apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: own-pipeline
spec:
  pipelineSpec:
    tasks:
    - name: own-pipeline
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.1.224
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: python:3.6.12-alpine
          name: build-python-unittest
          resources: {}
          script: |
            #!/bin/sh
            pip install -r requirements.txt
            pip install mysqlclient
            python ./manage.py test
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}