apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: newpipelinerun
    always_run: true
    context: "newpipelinerun"
    rerun_command: /newpipelinerun
    source: "newpipelinerun.yaml"
  - name: coverage
    always_run: true
    context: "coverage"
    rerun_command: /coverage
    source: "coverage.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
